tunnel: REPLACE_WITH_PROD_TUNNEL_ID
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: logam-mulia-antam.com
    path: ^/api
    service: http://backend:5000
  - hostname: logam-mulia-antam.com
    path: ^/uploads
    service: http://backend:5000
  - hostname: logam-mulia-antam.com
    service: http://frontend:3000
  - hostname: www.logam-mulia-antam.com
    path: ^/api
    service: http://backend:5000
  - hostname: www.logam-mulia-antam.com
    path: ^/uploads
    service: http://backend:5000
  - hostname: www.logam-mulia-antam.com
    service: http://frontend:3000
  - service: http_status:404
