INSERT INTO "payment_methods" ("code", "label", "description", "category", "is_active", "is_locked", "status", "config", "sort_order", "created_at", "updated_at")
VALUES
  (
    'duitku_bri_va',
    'BRI',
    'Pembayaran BRI Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"BR","imageUrl":"/images/payment/BRI.png"}'::jsonb,
    210,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_bni_va',
    'BNI',
    'Pembayaran BNI Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"I1","imageUrl":"/images/payment/duitku-bni.png"}'::jsonb,
    220,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_mandiri_va',
    'Mandiri',
    'Pembayaran Mandiri Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"M2","imageUrl":"/images/payment/Mandiri.png"}'::jsonb,
    230,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_cimb_va',
    'CIMB Niaga',
    'Pembayaran CIMB Niaga Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"B1","imageUrl":"/images/payment/CIMB.png"}'::jsonb,
    240,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_bsi_va',
    'BSI',
    'Pembayaran BSI Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"BV","imageUrl":"/images/payment/BSI.webp"}'::jsonb,
    250,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_danamon_va',
    'Danamon',
    'Pembayaran Danamon Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"DM","imageUrl":"/images/payment/Danamon.webp"}'::jsonb,
    260,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_permata_va',
    'Permata',
    'Pembayaran Permata Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"BT","imageUrl":"/images/payment/PERMATA.png"}'::jsonb,
    270,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_maybank_va',
    'Maybank',
    'Pembayaran Maybank Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"VA","imageUrl":"/images/payment/Maybank.png"}'::jsonb,
    280,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_sampoerna_va',
    'Sampoerna',
    'Pembayaran Bank Sahabat Sampoerna Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"S1","imageUrl":"/images/payment/Sampoerna.jpeg"}'::jsonb,
    290,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_artha_graha_va',
    'Artha Graha International',
    'Pembayaran Bank Artha Graha International via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"AG","imageUrl":"/images/payment/duitku-artha-graha.jpeg"}'::jsonb,
    300,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_neo_va',
    'Neo',
    'Pembayaran Bank Neo Commerce Virtual Account via Duitku.',
    'VIRTUAL_ACCOUNT',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"NC","imageUrl":"/images/payment/duitku-neo.webp"}'::jsonb,
    310,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_alfamart',
    'Alfamart',
    'Pembayaran retail Alfamart via Duitku.',
    'RETAIL',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"FT","imageUrl":"/images/payment/duitku-alfamart.png"}'::jsonb,
    320,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_pegadaian',
    'Pegadaian',
    'Pembayaran retail Pegadaian via Duitku.',
    'RETAIL',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"FT","imageUrl":"/images/payment/duitku-pegadaian.png"}'::jsonb,
    330,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ),
  (
    'duitku_pos',
    'POS Indonesia',
    'Pembayaran retail POS Indonesia via Duitku.',
    'RETAIL',
    false,
    false,
    'READY',
    '{"provider":"duitku","channel":"FT","imageUrl":"/images/payment/duitku-pos-indonesia.png"}'::jsonb,
    340,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  )
ON CONFLICT ("code") DO UPDATE
SET
  "label" = EXCLUDED."label",
  "description" = EXCLUDED."description",
  "category" = EXCLUDED."category",
  "is_locked" = EXCLUDED."is_locked",
  "status" = EXCLUDED."status",
  "config" = EXCLUDED."config",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = CURRENT_TIMESTAMP;
